version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - apt-get update
      - apt install maven -y
      - apt-get install openjdk-8-jdk -y
      - mvn clean install -f pom.xml

artifacts:
  files:
    - '**/*'
